name: Teddie
favicon: null
layout_spectrum: 0.7042526102159172
typography_spectrum: 0.7913184463977814
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7225235898513347
  lightness: 0.8088747854344547
  saturation: 0.653883836697787
  rhythmicContrast: 0.385267311707139
purpose: []
